# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Xilinx_project/HDL_projects_for_digital_circuit_course/Learning/ALU/ALU.srcs/sources_1/ip/ila/ila.xci
# IP: The module: 'ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/Learning/ALU/ALU.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/Learning/ALU/ALU.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/Learning/ALU/ALU.srcs/sources_1/ip/ila/ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Xilinx_project/HDL_projects_for_digital_circuit_course/Learning/ALU/ALU.srcs/sources_1/ip/ila/ila.xci
# IP: The module: 'ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/Learning/ALU/ALU.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/Learning/ALU/ALU.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/Learning/ALU/ALU.srcs/sources_1/ip/ila/ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
