webtalk_init -webtalk_dir D:/FPGA/project/mcu_1/mcu_1.sim/sim_1/behav/xsim/xsim.dir/top_tp_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul  9 14:22:58 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c5e28412-6fc5-4a1f-8f7e-2b80c9badb9c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d81ab2f525b24edebf789c16c63faacf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "16" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "7.44_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10716_KB" -context "xsim\\usage"
webtalk_transmit -clientid 891352682 -regid "" -xml D:/FPGA/project/mcu_1/mcu_1.sim/sim_1/behav/xsim/xsim.dir/top_tp_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/FPGA/project/mcu_1/mcu_1.sim/sim_1/behav/xsim/xsim.dir/top_tp_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/FPGA/project/mcu_1/mcu_1.sim/sim_1/behav/xsim/xsim.dir/top_tp_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
