set_property SRC_FILE_INFO {cfile:E:/Xilinx_project/HDL_projects_for_digital_circuit_course/MCU_ff/MCU_f.srcs/constrs_1/new/limit.xdc rfile:../../../MCU_f.srcs/constrs_1/new/limit.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports rst]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports light]
