# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/limit.xdc

# IP: ip/RAM/RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet
