# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/MCU_f/MCU_f.srcs/sources_1/ip/ROM/ROM.xci
# IP: The module: 'ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/MCU_f/MCU_f.gen/sources_1/ip/ROM/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/MCU_f/MCU_f.srcs/sources_1/ip/ROM/ROM.xci
# IP: The module: 'ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx_project/HDL_projects_for_digital_circuit_course/MCU_f/MCU_f.gen/sources_1/ip/ROM/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
